import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Brain, 
  Clock, 
  LineChart, 
  MessageCircle, 
  Gamepad2, 
  GraduationCap,
  Zap,
  Users,
  Target,
  CheckCircle2,
  ArrowRight
} from 'lucide-react';
import Layout from '../components/Layout';
import Link from '../components/Link';

const features = [
  {
    icon: Brain,
    title: "AI-Powered Study Guide",
    description: "Get personalized study materials and summaries generated by advanced AI algorithms tailored to your learning style.",
    details: [
      "Smart content summarization",
      "Personalized study recommendations",
      "Concept mapping and connections",
      "Adaptive learning paths"
    ]
  },
  {
    icon: Clock,
    title: "Personalized Timetable Generator",
    description: "Create optimal study schedules that adapt to your peak productivity hours and course requirements.",
    details: [
      "AI-powered schedule optimization",
      "Break time management",
      "Deadline tracking",
      "Calendar integration"
    ]
  },
  {
    icon: LineChart,
    title: "Progress Tracker with Graphs",
    description: "Visualize your learning journey with detailed analytics and performance insights across subjects.",
    details: [
      "Real-time performance metrics",
      "Subject-wise analysis",
      "Progress predictions",
      "Custom goal tracking"
    ]
  },
  {
    icon: MessageCircle,
    title: "Interactive Chatbot Mentor",
    description: "24/7 AI tutor to answer questions, explain concepts, and guide your study sessions.",
    details: [
      "Instant doubt resolution",
      "Concept explanations",
      "Practice problem generation",
      "Study technique suggestions"
    ]
  },
  {
    icon: Gamepad2,
    title: "Gamified Quizzes",
    description: "Make learning fun with interactive quizzes, achievements, and competitive elements.",
    details: [
      "Dynamic quiz generation",
      "Competitive leaderboards",
      "Achievement badges",
      "Peer challenges"
    ]
  },
  {
    icon: GraduationCap,
    title: "Dedicated Teacher Panel",
    description: "Comprehensive tools for educators to track, assess, and support student progress.",
    details: [
      "Student performance monitoring",
      "Assignment management",
      "Automated grading",
      "Parent communication"
    ]
  },
  {
    icon: Zap,
    title: "Smart Practice Tests",
    description: "AI-generated practice tests that adapt to your knowledge gaps and learning progress.",
    details: [
      "Adaptive difficulty levels",
      "Weakness identification",
      "Targeted practice",
      "Performance analytics"
    ]
  },
  {
    icon: Users,
    title: "Collaborative Study Groups",
    description: "Form virtual study groups, share resources, and learn together in real-time.",
    details: [
      "Virtual study rooms",
      "Resource sharing",
      "Group discussions",
      "Peer tutoring"
    ]
  },
  {
    icon: Target,
    title: "Goal Setting & Tracking",
    description: "Set academic goals, track milestones, and celebrate your achievements.",
    details: [
      "Smart goal recommendations",
      "Progress milestones",
      "Achievement celebrations",
      "Performance insights"
    ]
  }
];

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2
    }
  }
};

const item = {
  hidden: { opacity: 0, y: 20 },
  show: { opacity: 1, y: 0 }
};

const FeaturesPage: React.FC = () => {
  const [selectedFeature, setSelectedFeature] = useState<number | null>(null);

  return (
    <Layout>
      <div className="min-h-screen bg-gradient-to-b from-[#06142E] to-[#1B3B6F]">
        {/* Hero Section */}
        <div className="pt-32 pb-20 px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, scale: 0.9 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ duration: 0.5 }}
              className="inline-block mb-6 p-2 bg-indigo-800 rounded-full"
            >
              <div className="px-4 py-1 bg-indigo-700 rounded-full">
                <span className="text-indigo-200">✨ Experience the future of learning</span>
              </div>
            </motion.div>
            
            <motion.h1 
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="text-4xl md:text-5xl font-bold text-white mb-6"
            >
              Why Choose Learnex?
            </motion.h1>
            <motion.p 
              initial={{ opacity: 0, y: -20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.4 }}
              className="text-xl text-indigo-200 max-w-3xl mx-auto"
            >
              Built for students, powered by AI. Transform your learning experience with cutting-edge technology and personalized education.
            </motion.p>
          </div>
        </div>

        {/* Features Grid */}
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
          <motion.div 
            variants={container}
            initial="hidden"
            whileInView="show"
            viewport={{ once: true }}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {features.map((feature, index) => {
              const Icon = feature.icon;
              const isSelected = selectedFeature === index;
              
              return (
                <motion.div
                  key={index}
                  variants={item}
                  className={`bg-white rounded-2xl p-8 shadow-lg cursor-pointer transform transition-all duration-300 ${
                    isSelected ? 'scale-105 ring-2 ring-indigo-500' : 'hover:scale-105'
                  }`}
                  onClick={() => setSelectedFeature(isSelected ? null : index)}
                >
                  <div className="h-14 w-14 rounded-xl bg-indigo-100 flex items-center justify-center mb-6">
                    <Icon className="h-8 w-8 text-indigo-900" />
                  </div>
                  <h3 className="text-xl font-bold text-gray-900 mb-3">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 leading-relaxed mb-4">
                    {feature.description}
                  </p>
                  
                  <AnimatePresence>
                    {isSelected && (
                      <motion.div
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        exit={{ opacity: 0, height: 0 }}
                        transition={{ duration: 0.3 }}
                        className="border-t border-gray-200 pt-4 mt-4"
                      >
                        <ul className="space-y-2">
                          {feature.details.map((detail, detailIndex) => (
                            <motion.li
                              key={detailIndex}
                              initial={{ opacity: 0, x: -20 }}
                              animate={{ opacity: 1, x: 0 }}
                              transition={{ delay: detailIndex * 0.1 }}
                              className="flex items-center text-gray-700"
                            >
                              <CheckCircle2 className="h-5 w-5 text-green-500 mr-2" />
                              {detail}
                            </motion.li>
                          ))}
                        </ul>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </motion.div>
              );
            })}
          </motion.div>
        </div>

        {/* CTA Section */}
        <div className="bg-indigo-900 py-16">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-indigo-800 rounded-2xl p-8 md:p-12 relative overflow-hidden">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                className="relative z-10"
              >
                <h2 className="text-3xl md:text-4xl font-bold text-white mb-6 max-w-2xl">
                  Ready to Transform Your Learning Journey?
                </h2>
                <p className="text-xl text-indigo-200 mb-8 max-w-2xl">
                  Join thousands of students already using Learnex to achieve their academic goals.
                </p>
                <Link to="/signup">
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    className="bg-white text-indigo-900 px-8 py-3 rounded-xl font-semibold text-lg shadow-lg hover:bg-indigo-50 transition-colors duration-200 flex items-center"
                  >
                    Get Started Free
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </motion.button>
                </Link>
              </motion.div>
              
              {/* Background Pattern */}
              <div className="absolute top-0 right-0 w-1/2 h-full opacity-10">
                <div className="absolute inset-0 bg-gradient-to-r from-indigo-800 to-transparent" />
                <svg className="w-full h-full" viewBox="0 0 100 100" preserveAspectRatio="none">
                  <defs>
                    <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
                      <path d="M 10 0 L 0 0 0 10" fill="none" stroke="currentColor" strokeWidth="0.5" />
                    </pattern>
                  </defs>
                  <rect width="100" height="100" fill="url(#grid)" />
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default FeaturesPage;